Repository Rev3rseSecurity/WebMap, pull requests merged in 2018-12, with the labels that each got.

#47 fix port count in xml list
  functions.py
  views.py
Labels: bug

#62 Update nmap_newscan(request)
  functions_nmap.py
Labels: improvements

#64 Improve regex filters
  functions_nmap.py
  static/async.js
Labels: improvements

#69 Update async.js
  static/async.js
Labels: improvements

#68 Targets via target file
  functions_nmap.py
Labels: enhancement
